"""API request/response schemas (Pydantic, camelCase JSON)."""
from app.schemas.analytics import (
    BatchInspectionOut,
    BatchStats,
    DashboardSummary,
    InspectionStatusBreakdown,
    RecurringViolation,
)
from app.schemas.audit import AuditEventOut, ModelVersionOut
from app.schemas.common import HealthResponse, Message, Paginated
from app.schemas.compliance import (
    ComplianceErrorOut,
    ComplianceEvaluationOut,
    ComplianceRuleOut,
    ComplianceStatusOut,
    EngineFindingOut,
    EngineInfoOut,
    EvaluateRequest,
    EvaluateResponse,
    RuleTypeOut,
)
from app.schemas.evidence_graph import EvidenceGraph, EvidenceGraphEdge, EvidenceGraphNode
from app.schemas.evidence_trace import (
    EvidenceGraphOut,
    EvidenceStrengthInfo,
    TraceEdge,
    TraceNode,
)
from app.schemas.finding import EvidenceOut, FindingOut, ReviewActionOut, ReviewFindingRequest
from app.schemas.image import (
    BoundingBox,
    ExtractedFieldOut,
    ImageOut,
    ImageRegionOut,
    RegisterImageRequest,
)
from app.schemas.inspection import (
    AnalyzeInspectionRequest,
    CreateInspectionRequest,
    FindingCounts,
    InspectionDetailOut,
    InspectionSummaryOut,
    PackageOut,
)
from app.schemas.product import ProductOut
from app.schemas.regulatory import (
    CandidateRequirementOut,
    FieldCandidateOut,
    FieldCandidatesOut,
    PaginatedRequirements,
    RegulationOut,
    RegulatoryDocumentOut,
    RegulatoryRequirementDetailOut,
    RegulatoryRequirementOut,
    RegulatorySourceOut,
    RegulatorySourceUpdateIn,
    RegulatoryVersionOut,
    RequirementProvenanceOut,
    RuleApplicabilityOut,
    RuleOut,
    VersionSelectionOut,
)
from app.schemas.user import AuthTokenResponse, LoginRequest, UserOut

__all__ = [
    "AnalyzeInspectionRequest",
    "AuditEventOut",
    "AuthTokenResponse",
    "BatchInspectionOut",
    "BatchStats",
    "BoundingBox",
    "CandidateRequirementOut",
    "ComplianceErrorOut",
    "ComplianceEvaluationOut",
    "ComplianceRuleOut",
    "ComplianceStatusOut",
    "CreateInspectionRequest",
    "DashboardSummary",
    "EvidenceGraph",
    "EvidenceGraphEdge",
    "EvidenceGraphNode",
    "EvidenceGraphOut",
    "EvidenceOut",
    "EvidenceStrengthInfo",
    "ExtractedFieldOut",
    "FieldCandidateOut",
    "FieldCandidatesOut",
    "EngineFindingOut",
    "EngineInfoOut",
    "EvaluateRequest",
    "EvaluateResponse",
    "FindingCounts",
    "FindingOut",
    "HealthResponse",
    "ImageOut",
    "ImageRegionOut",
    "InspectionDetailOut",
    "InspectionStatusBreakdown",
    "InspectionSummaryOut",
    "LoginRequest",
    "Message",
    "ModelVersionOut",
    "PackageOut",
    "Paginated",
    "PaginatedRequirements",
    "ProductOut",
    "RecurringViolation",
    "RegisterImageRequest",
    "RegulationOut",
    "RegulatoryDocumentOut",
    "RegulatoryRequirementDetailOut",
    "RegulatoryRequirementOut",
    "RegulatorySourceOut",
    "RegulatorySourceUpdateIn",
    "RegulatoryVersionOut",
    "RequirementProvenanceOut",
    "ReviewActionOut",
    "ReviewFindingRequest",
    "RuleApplicabilityOut",
    "RuleOut",
    "RuleTypeOut",
    "TraceEdge",
    "TraceNode",
    "UserOut",
    "VersionSelectionOut",
]
