"""initial schema

Revision ID: 3d657d928700
Revises: 
Create Date: 2026-08-23 23:40:53.769399
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d657d928700'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('service_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions'))
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_service_type'), ['service_type'], unique=False)

    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('gtin', sa.String(length=64), nullable=True),
    sa.Column('declaration_profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_gtin'), ['gtin'], unique=False)

    op.create_table('regulations',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('jurisdiction', sa.String(length=120), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('official_source_url', sa.String(length=1024), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulations'))
    )
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulations_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_regulations_created_at'), ['created_at'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('batch_inspections',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_batch_inspections_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batch_inspections'))
    )
    with op.batch_alter_table('batch_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_inspections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_inspections_status'), ['status'], unique=False)

    op.create_table('regulation_versions',
    sa.Column('regulation_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amendment_of_id', sa.Uuid(), nullable=True),
    sa.Column('source_document_ref', sa.String(length=512), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amendment_of_id'], ['regulation_versions.id'], name=op.f('fk_regulation_versions_amendment_of_id_regulation_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], name=op.f('fk_regulation_versions_regulation_id_regulations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regulation_versions'))
    )
    with op.batch_alter_table('regulation_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulation_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_versions_regulation_id'), ['regulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_regulation_versions_status'), ['status'], unique=False)

    op.create_table('inspections',
    sa.Column('reference_no', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('inspector_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('context_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_inspections.id'], name=op.f('fk_inspections_batch_id_batch_inspections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], name=op.f('fk_inspections_inspector_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inspections_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspections'))
    )
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspections_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_inspector_id'), ['inspector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspections_reference_no'), ['reference_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_inspections_status'), ['status'], unique=False)

    op.create_table('rules',
    sa.Column('regulation_version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('requirement_summary', sa.Text(), nullable=False),
    sa.Column('validation_logic_ref', sa.String(length=120), nullable=False),
    sa.Column('evidence_requirement', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['regulation_version_id'], ['regulation_versions.id'], name=op.f('fk_rules_regulation_version_id_regulation_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_regulation_version_id'), ['regulation_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_rule_code'), ['rule_code'], unique=False)

    op.create_table('audit_events',
    sa.Column('inspection_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_audit_events_inspection_id_inspections'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('packages',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_packages_inspection_id_inspections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_packages_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages'))
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_inspection_id'), ['inspection_id'], unique=False)

    op.create_table('rule_applicability',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('product_category', sa.String(length=120), nullable=False),
    sa.Column('condition_expression', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_applicability_rule_id_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_applicability'))
    )
    with op.batch_alter_table('rule_applicability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_applicability_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_applicability_product_category'), ['product_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_applicability_rule_id'), ['rule_id'], unique=False)

    op.create_table('compliance_findings',
    sa.Column('inspection_id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('rule_version_id', sa.Uuid(), nullable=True),
    sa.Column('field_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], name=op.f('fk_compliance_findings_inspection_id_inspections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_compliance_findings_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_compliance_findings_package_id_packages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_compliance_findings_rule_id_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['regulation_versions.id'], name=op.f('fk_compliance_findings_rule_version_id_regulation_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_findings'))
    )
    with op.batch_alter_table('compliance_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_findings_field_type'), ['field_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_findings_inspection_id'), ['inspection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_findings_package_id'), ['package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_findings_status'), ['status'], unique=False)

    op.create_table('images',
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('image_type', sa.String(length=16), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=24), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_images_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_images'))
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_package_id'), ['package_id'], unique=False)

    op.create_table('image_regions',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('region_type', sa.String(length=24), nullable=False),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_image_regions_image_id_images'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_regions'))
    )
    with op.batch_alter_table('image_regions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_image_regions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_image_regions_image_id'), ['image_id'], unique=False)

    op.create_table('review_actions',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('corrected_status', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['compliance_findings.id'], name=op.f('fk_review_actions_finding_id_compliance_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_actions_reviewer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_actions'))
    )
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_actions_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_actions_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('image_region_id', sa.Uuid(), nullable=True),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_extracted_fields_image_id_images'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_region_id'], ['image_regions.id'], name=op.f('fk_extracted_fields_image_region_id_image_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_extracted_fields_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_extracted_fields_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_fields'))
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_type'), ['field_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_image_id'), ['image_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_image_region_id'), ['image_region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_package_id'), ['package_id'], unique=False)

    op.create_table('evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('image_region_id', sa.Uuid(), nullable=True),
    sa.Column('extracted_field_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_fields.id'], name=op.f('fk_evidence_extracted_field_id_extracted_fields'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['compliance_findings.id'], name=op.f('fk_evidence_finding_id_compliance_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name=op.f('fk_evidence_image_id_images'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_region_id'], ['image_regions.id'], name=op.f('fk_evidence_image_region_id_image_regions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_evidence_rule_id_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_created_at'))

    op.drop_table('evidence')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_package_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_image_region_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_image_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_type'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_created_at'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_actions_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_review_actions_finding_id'))
        batch_op.drop_index(batch_op.f('ix_review_actions_created_at'))

    op.drop_table('review_actions')
    with op.batch_alter_table('image_regions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_regions_image_id'))
        batch_op.drop_index(batch_op.f('ix_image_regions_created_at'))

    op.drop_table('image_regions')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_package_id'))
        batch_op.drop_index(batch_op.f('ix_images_created_at'))

    op.drop_table('images')
    with op.batch_alter_table('compliance_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_findings_status'))
        batch_op.drop_index(batch_op.f('ix_compliance_findings_package_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_findings_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_findings_field_type'))
        batch_op.drop_index(batch_op.f('ix_compliance_findings_created_at'))

    op.drop_table('compliance_findings')
    with op.batch_alter_table('rule_applicability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_applicability_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_applicability_product_category'))
        batch_op.drop_index(batch_op.f('ix_rule_applicability_created_at'))

    op.drop_table('rule_applicability')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_packages_created_at'))

    op.drop_table('packages')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_inspection_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_rule_code'))
        batch_op.drop_index(batch_op.f('ix_rules_regulation_version_id'))
        batch_op.drop_index(batch_op.f('ix_rules_created_at'))

    op.drop_table('rules')
    with op.batch_alter_table('inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspections_status'))
        batch_op.drop_index(batch_op.f('ix_inspections_reference_no'))
        batch_op.drop_index(batch_op.f('ix_inspections_inspector_id'))
        batch_op.drop_index(batch_op.f('ix_inspections_created_at'))
        batch_op.drop_index(batch_op.f('ix_inspections_batch_id'))

    op.drop_table('inspections')
    with op.batch_alter_table('regulation_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulation_versions_status'))
        batch_op.drop_index(batch_op.f('ix_regulation_versions_regulation_id'))
        batch_op.drop_index(batch_op.f('ix_regulation_versions_created_at'))

    op.drop_table('regulation_versions')
    with op.batch_alter_table('batch_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_inspections_status'))
        batch_op.drop_index(batch_op.f('ix_batch_inspections_created_at'))

    op.drop_table('batch_inspections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulations_created_at'))
        batch_op.drop_index(batch_op.f('ix_regulations_code'))

    op.drop_table('regulations')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_gtin'))
        batch_op.drop_index(batch_op.f('ix_products_created_at'))
        batch_op.drop_index(batch_op.f('ix_products_category'))

    op.drop_table('products')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_service_type'))
        batch_op.drop_index(batch_op.f('ix_model_versions_created_at'))

    op.drop_table('model_versions')
    # ### end Alembic commands ###
